Document: xevd-base
Title: Debian xevd-base Manual
Author: <insert document author here>
Abstract: This manual describes what xevd-base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xevd-base/xevd-base.sgml.gz

Format: postscript
Files: /usr/share/doc/xevd-base/xevd-base.ps.gz

Format: text
Files: /usr/share/doc/xevd-base/xevd-base.text.gz

Format: HTML
Index: /usr/share/doc/xevd-base/html/index.html
Files: /usr/share/doc/xevd-base/html/*.html
