Document: xevd-main
Title: Debian xevd-main Manual
Author: <insert document author here>
Abstract: This manual describes what xevd-main is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xevd-main/xevd-main.sgml.gz

Format: postscript
Files: /usr/share/doc/xevd-main/xevd-main.ps.gz

Format: text
Files: /usr/share/doc/xevd-main/xevd-main.text.gz

Format: HTML
Index: /usr/share/doc/xevd-main/html/index.html
Files: /usr/share/doc/xevd-main/html/*.html
